version: "3.7"

services:
  frontend:
    image: "karaokeparty/frontend:$BRANCH"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.karaokeparty-frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.karaokeparty-frontend.entrypoints=websecure"
      - "traefik.http.routers.karaokeparty-frontend.tls.certresolver=letsencrypt"
  backend:
    image: "karaokeparty/backend:$BRANCH"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.karaokeparty-backend.rule=Host(`${DOMAIN}`) && Path(`/api`)"
      - "traefik.http.routers.karaokeparty-backend.entrypoints=websecure"
      - "traefik.http.routers.karaokeparty-backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.karaokeparty-backend.middlewares=karaokeparty-backend-strip-prefix@docker"
      - "traefik.http.middlewares.karaokeparty-backend-strip-prefix.stripprefix.prefixes=/api"

networks:
  traefik:
    external: true
