version: "3.7"

services:
  frontend:
    image: "karaokeparty/frontend:$BRANCH"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.karaokeparty-frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.karaokeparty-frontend.entrypoints=websecure"
      - "traefik.http.routers.karaokeparty-frontend.tls.certresolver=letsencrypt"
  backend:
    image: "karaokeparty/backend:$BRANCH"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.karaokeparty-backend.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.karaokeparty-backend.entrypoints=websecure"
      - "traefik.http.routers.karaokeparty-backend.tls.certresolver=letsencrypt"
    volumes:
      - /var/karaokeparty/data:/app/data

networks:
  traefik:
    external: true
