name: publish

on: [push]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/${GCLOUD_PROJECT}/frontend:${GITHUB_REF##*/} .

      - name: Push
        run: |
          docker push gcr.io/${GCLOUD_PROJECT}/frontend:${GITHUB_REF##*/}

      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/${GCLOUD_PROJECT}/frontend:${GITHUB_REF##*/}
          service: karaokeparty-frontend

