name: publish

on: [push]

jobs:
  build:
    name: Cloud Run Deployment Frontend
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Branch name
        shell: bash
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"


      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ env.GCLOUD_PROJECT }}/frontend:${{ steps.extract_branch.outputs.branch }} -f docker/frontend.Dockerfile .

      - name: Push
        run: |
          docker push gcr.io/${{ env.GCLOUD_PROJECT }}/frontend:${{ steps.extract_branch.outputs.branch }}

      - name: Deploy
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/${{ env.GCLOUD_PROJECT }}/frontend:${{ steps.extract_branch.outputs.branch }}
          service: karaokeparty-frontend-${{ steps.extract_branch.outputs.branch }}

